# Assignments

Abgabeaufgaben sind wissenschaftliche Dokumente, deren Einreichung in einer spezifischen Form erfolgen muss. Jede dieser Formen verfolgt einen gesonderten Zweck und bringt entsprechende Formatvorgaben mit sich. Ziel der nachfolgenden Formatbeschreibungen ist die Unterstützung der Sicherung [guter wissenschaftlicher Praxis](https://www.dfg.de/foerderung/grundlagen_rahmenbedingungen/gwp/). Die Deutsche Forschungsgemeinschaft (DFG) definiert als [allgemeine Prinzipien](https://www.dfg.de/download/pdf/foerderung/rechtliche_rahmenbedingungen/gute_wissenschaftliche_praxis/empfehlung_wiss_praxis_1310.pdf) wissenschaftlicher Arbeiten, insbesondere:

- lege artis zu arbeiten,
- Resultate zu dokumentieren,
- alle Ergebnisse konsequent selbst anzuzweifeln,
- strikte Ehrlichkeit im Hinblick auf die Beiträge von Partnern, Konkurrenten und
Vorgängern zu wahren.

Diese allgemeinen Prinzipien wissenschaftlicher Arbeit sind formatübergreifend und jeder Zeit zu beachten. Die nachfolgende Auflistung geht spezifischer auf die Besonderheiten der möglichen Abgabeformate ein.

## Paper

Paper sind wissenschaftliche Dokumente, die üblicherweise den Prozess zur Erzielung eines Erkenntnisgewinns transparent und in der Form darstellen, dass die erzielten Resultate für den fachlichen Leser nachvollziehbar sind. 

- **FHSWF Markdown Template:** Das FHSWF R Package enthält die Formatvorlage `fhswf::seminarpaper`, die für die Erstellung von Hausarbeiten, Projektarbeiten oder Abschlussarbeiten verwendet werden kann. Text kann in diesem Template im Markdown Format integriert und formatiert werden, alle Erweiterungen des [R Markdown](https://rmarkdown.rstudio.com/) Dialektes werden unterstützt. Diese Vorlage ist zudem voll \LaTeX kompatibel. Im Unterschied zu reinem \LaTeX erlaubt dieses Template die Integration von beliebigem Programmcode (R, Python, C, ...) der beim Erstellen des PDFs ausgeführt werden kann. Programmcode wird automatisch ausgeführt und deren Ergebnisse (Konsolenoutput, Tabellen, Grafiken) können im erstellten Dokument automatisch integriert werden, sodass diese nicht separat verwaltet werden müssen.
- **\LaTeX:** 

## Präsentation


### Typ: Wissensvermittlung (K)

### Typ: Ergebnisvorstellung (R)

Unabhängig vom genauen Typ der Präsentation ist ein angemessenes Format zu wählen, dass allen wissenschaftlichen Belangen (z.B. Angabe von Quellen) ermöglicht. 

### Tool: PowerPoint (P)

Bitte nutzen sie die folgende Powerpoint Vorlage für die Erstellung der Präsentation.

### Tool: Markdown (M)


## Implementierung


## Frei